# docker-compose.yml
vendors:
  image: python:2.7
  working_dir: /mnt
  volumes:
    - .:/mnt
  environment:
    PYTHONUSERBASE: /mnt/vendor
  command: pip install -r requirements.txt

web:
  build: .
  command: python server.py 9000
  ports:
    - "9000:9000"
